### ISSUE TITLE
Image list is empty in gallery

### ISSUE THREAD

**Issue by teewhey** [tranduyhung/grav-theme-big-picture#12]
I have uploaded a few pictures in the gallery using the admin plugin.
Image was successfully uploaded and saved. 

However when I go to the Images tab to create an item, the list is somehow empty.
<img width="964" alt="image" src="https://user-images.githubusercontent.com/4113595/34253110-39024c40-e681-11e7-88fb-e72e96d858fc.png">
<img width="868" alt="image" src="https://user-images.githubusercontent.com/4113595/34253124-464ae754-e681-11e7-818d-525a7bd928c4.png">

Any idea?

**Comment by tranduyhung** [comment]
If you refresh or save the page, are the images shown after that?

**Comment by teewhey** [comment]
Nope. Nothing on the drop down list. I've used different browser & also private browsing mode.

**Comment by tranduyhung** [comment]
I'm not sure if it is a problem from ```filepicker``` field or from us. Grav's ```filepicker``` field doesn't consider ".JPG" extension as ".jpg". You have 2 solutions:

* Rename your images to *.jpg
* Edit user/themes/big-picture/blueprints/modular/gallery.yaml and add ".JPG" to the list of ```header.images```, the result looks like this:

```
            header.images:
              name: images
              type: list
              style: vertical
              label: Images
              fields:
                .title:
                  type: text
                  label: Title
                  help: Image's title.
                .full:
                  type: filepicker
                  folder: '@self'
                  preview_images: true
                  accept:
                    - .png
                    - .jpg
                    - .JPG
                  label: Full Image
                  help: Full image's filename.
```

I will need to contact Grav developer for their comments.
