### ISSUE TITLE
Usuage

### ISSUE THREAD

**Issue by Dan458** [tranduyhung/grav-theme-big-picture#2]
Hi,

Im trying to use your theme but having some difficulties. 

I set the Home page to be type modular, I then create some modular pages of various types  intro, info, contact etc and set their parent to be Home. However the navigation buttons to go to the next section don't appear. 

Any suggestions on what maybe wrong with my setup?

Thanks
Dan

**Comment by tranduyhung** [comment]
Hi Dan,

What is the name of your home page's folder? If it is not "home" you can try to rename it to "home".

Regards,
Hung

**Comment by Dan458** [comment]
Hi Hung,

Thanks for the reply. The home page folder is currently > "Website Directory"/user/pages/01.Home 

The 01.Home folder then contains:

_welcome --> intro.md
_get-in-touch --> contact.md
_what-i-do --> info.md
modular.md

Thanks
Dan

**Comment by tranduyhung** [comment]
In your home's modular.md, have you order your modular pages in custom order? Similar to this:

```
title: Home
content:
    items: '@self.modular'
    order:
        by: default
        dir: asc
        custom:
            - _intro
            - _what-i-do
            - _who-i-am
            - _my-work
            - _contact
```

The template follows this order defined in "custom" to find the next section on the page.
